### ISSUE TITLE
PHP 5.5 incompatible?

### ISSUE THREAD

**Issue by garyross** [bigwhoop/sentence-breaker#2]
Your composer file requires PHP 5.6. Is this actually the case? 

A deal-breaker for those running something like Ubuntu 14.0.4 LTS.

**Comment by bigwhoop** [comment]
Hi Gary, 

the official support for PHP 5.5 has ended almost a year ago. In a couple of weeks the official security support will also end. http://php.net/supported-versions.php

I'm not sure what Canonical will do (probably backport patches from 5.6?) with 14.04 though.

Personally I haven't tested this project against PHP 5.5 and am not sure if it would work. Haven't looked at the code in a while.

**Comment by garyross** [comment]
Hi Philippe,
Thanks for the quick reply! 

Ubuntu 14.0.4 LTS as an LTS release is supported until 2019, so I guess they'll backport the patches. My understanding is that they will never upgrade PHP beyond 5.5.

I'm going to fork your project, change the requirement to 5.5 and let you know if there are any issues. I'd be surprised if you have 5.6 specific requirements, but you never know!
Gary

**Comment by garyross** [comment]
There are in fact a number of (minor) PHP 5.6 requirements. PHP 5.5 doesn't allow constant arrays
`const CHARS = [' ', "\t", "\r", "\n"];`
In my 'fork', I just changed to 
`public static $CHARS = [' ', "\t", "\r", "\n"];`

Other than that, works really well!

**Comment by bigwhoop** [comment]
For the reasons state above I'll close this issue. I don't think adding support for an outdated version of PHP is a good idea. If needed, people can always fork the repo.
