### ISSUE TITLE
Use generators to reduce memory consumption on lengthy text

### ISSUE THREAD

**Issue by dinamic** [bigwhoop/sentence-breaker#9]

**Comment by bcremer** [comment]
Hi @dinamic,

I'm currently working on a fully lazy and generator based implementation here: https://github.com/bigwhoop/sentence-breaker/pull/13

Please feel free to try and give feedback.

**Comment by bigwhoop** [comment]
The implementation was finished by @bcremer and has been merged and released in version 4.
